<?php
if( function_exists('acf_add_local_field_group') ){
    acf_add_local_field_group(array(
        'key' => 'group_632e49241698e',
        'title' => 'Calculadora',
        'fields' => array(
            array(
                'key' => 'field_632e492304b01',
                'label' => 'Titulo do resultado',
                'name' => 'titulo_do_resultado',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Resultado da margem consignável',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_632e49d604b02',
                'label' => 'Titulo da margem permitida',
                'name' => 'titulo_da_margem_permitida',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Margem permitida',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_632e49f004b03',
                'label' => 'Descrição da margem permitida',
                'name' => 'descricao_da_margem_permitida',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_632e4bd32d430',
                'label' => 'Titulo da margem disponível',
                'name' => 'titulo_da_margem_disponivel',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Margem disponível',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_632e4a1604b04',
                'label' => 'Descrição da margem disponível',
                'name' => 'descricao_da_margem_disponivel',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_632e4a3204b05',
                'label' => 'Valor do benefício',
                'name' => 'valor_do_beneficio',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Valor do benefício / salário',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_632e4a5f04b06',
                'label' => 'Parcela de empréstimo',
                'name' => 'parcela_de_emprestimo',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Parcela de empréstimo do benefício',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_632e492304b07',
                'label' => 'Porcentagem da margem permitida (35 significa 35%)',
                'name' => 'porcentagem_da_margem_permitida',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '35',
                'maxlength' => '',
                'placeholder' => '35',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_623e42273281',
                'label' => 'Titulo da dica no primeiro campo',
                'name'  => 'title_info_input_one',
                'type' => 'text',
                'instruction' => 'insira o titulo referente a dica do campo um',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' =>'',
                    'id'    => ''
                ),
                'default_value' => 'Titulo Dica Campo um',
                'maxlength'     => '',
                'placeholder'   => 'Titulo a ser inserido na dica do campo um',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key' => 'field_623e4787379',
                'label' => 'Texto para compor a ajuda no primeiro campo esquerdo',
                'name' => 'infor_input_one',
                'type' => 'text',
                'instruction' => 'insira as informações de ajuda para o campo um',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value' => 'Dica campo um',
                'maxlength'     => '',
                'placeholder'   => 'Dica a ser exibida campo um',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key' => 'field_623e42273282',
                'label' => 'Titulo da dica no segundo campo',
                'name'  => 'title_info_input_two',
                'type' => 'text',
                'instruction' => 'insira o titulo referente a dica do campo dois',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' =>'',
                    'id'    => ''
                ),
                'default_value' => 'Titulo Dica Campo dois',
                'maxlength'     => '',
                'placeholder'   => 'Titulo a ser inserido na dica do campo dois',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key' => 'field_623e4787372',
                'label' => 'Texto para compor a ajuda no segundo campo direito',
                'name' => 'infor_input_two',
                'type' => 'text',
                'instruction' => 'insira as informações de ajuda para o campo dois',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value' => 'Texto dica campo dois',
                'maxlength'     => '',
                'placeholder'   => 'Dica a ser exibida campo dois',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key' => 'field_623e42273283',
                'label' => 'Titulo da dica no primeiro campo de resultado',
                'name'  => 'title_result_input_one',
                'type' => 'text',
                'instruction' => 'insira o titulo referente a dica do campo um de resultado',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' =>'',
                    'id'    => ''
                ),
                'default_value' => 'Titulo dica campo um de resultado',
                'maxlength'     => '',
                'placeholder'   => 'Titulo a ser inserido na dica do campo um de resultado',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key' => 'field_623e4787373',
                'label' => 'Texto para compor a ajuda no primeiro campo de resultado',
                'name' => 'infor_input_result_one',
                'type' => 'text',
                'instruction' => 'insira as informações de ajuda para o campo um no resultado',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value' => 'Texto dica campo de resultado um',
                'maxlength'     => '',
                'placeholder'   => 'Dica a ser exibida no primeiro campo de resultado',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key' => 'field_623e42273284',
                'label' => 'Titulo da dica no segundo campo de resultado',
                'name'  => 'title_result_input_two',
                'type' => 'text',
                'instruction' => 'insira o titulo referente a dica do campo dois de resultado',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' =>'',
                    'id'    => ''
                ),
                'default_value' => 'Titulo dica campo dois de resultado',
                'maxlength'     => '',
                'placeholder'   => 'Titulo a ser inserido na dica do campo dois de resultado',
                'prepend'       => '',
                'append'        => '',
            ),
            array(
                'key' => 'field_623e4787374',
                'label' => 'Texto para compor a ajuda no segundo campo de resultado',
                'name' => 'infor_input_result_two',
                'type' => 'text',
                'instruction' => 'insira as informações de ajuda para o campo dois no resultado',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value' => 'Texto dica campo de resultado dois',
                'maxlength'     => '',
                'placeholder'   => 'Dica a ser exibida no segundo campo de resultado',
                'prepend'       => '',
                'append'        => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'calculadora',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
}