<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitff8998a1de7383fd61409cc2742d717e
{
    public static $files = array (
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        '37a3dc5111fe8f707wdwwcs2d2d2d232' => __DIR__ . '/..' . '/picr/php-autopilothq/src/AutopilotContact.php',
        '37a3dc5111fe8wdw7ab4scs2d2d2d232' => __DIR__ . '/..' . '/picr/php-autopilothq/src/AutopilotException.php',
        '37a3dccsc1fe8f707ab4scs2d2d2d232' => __DIR__ . '/..' . '/picr/php-autopilothq/src/AutopilotField.php',
        '37a3dc5111fe8f70712213d333d2d232' => __DIR__ . '/..' . '/picr/php-autopilothq/src/AutopilotManager.php',
    );

    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tests\\' => 6,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
        'A' => 
        array (
            'MasterPopups\\Autopilot\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/picr/php-autopilothq/tests',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Autopilot\\' => 
        array (
            0 => __DIR__ . '/..' . '/picr/php-autopilothq/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitff8998a1de7383fd61409cc2742d717e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitff8998a1de7383fd61409cc2742d717e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
