<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'c964ee0ededf28c96ebd9db5099ef910' => $vendorDir . '/guzzlehttp/promises/src/functions_include.php',
    'a0edc8309cc5e1d60e3047b5df6b7052' => $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    '37a3dc5111fe8f707ab4c132ef1dbc62' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    '37a3dc5111fe8f707wdwwcs2d2d2d232' => $vendorDir . '/picr/php-autopilothq/src/AutopilotContact.php',
    '37a3dc5111fe8wdw7ab4scs2d2d2d232' => $vendorDir . '/picr/php-autopilothq/src/AutopilotException.php',
    '37a3dccsc1fe8f707ab4scs2d2d2d232' => $vendorDir . '/picr/php-autopilothq/src/AutopilotField.php',
    '37a3dc5111fe8f70712213d333d2d232' => $vendorDir . '/picr/php-autopilothq/src/AutopilotManager.php',
);
